### ISSUE TITLE
Ilum License

### ISSUE THREAD

**Issue by kamrar** [ilum-cloud/doc#1]
Hi Ilum,

What is the license for your software? I used this documentation to run some spark jobs through your API in our SaaS platform, but I'm not sure if I'm breaking the Ilum license by doing that.

In addition, please update the documentation as we had to dig out most of the stuff from your repository and helm files.

**Comment by thijs-s** [comment]
Hello @kamrar! Thank you for choosing Ilum to accomplish your goals. We are pleased that you found us. Our software hasn't had a public release yet. Current documentation is only for a reference for further versions. At the actual state, Ilum is a closed source software that we are planning to open in the future, but the 'beta' version published in our repository will be free so you can use it without any limitations.

We will update the documentation. Thank you for signalling it.
You can 'watch' our repository to be notified about the updates.
